name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  GHCR_SLUG: ghcr.io/distribution/distribution

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.20.8
          - 1.21.1
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      -
        name: Test
        run: |
          make coverage
      -
        name: Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./

  build:
    permissions:
      id-token: write # to write to GHCR
      packages: write # to write to GHCR

    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GHCR_SLUG }}
          ### push on PRs and main
          # ghcr.io/distribution/distribution:pr<number>
          # ghcr.io/distribution/distribution:sha<sha>
          # ghcr.io/distribution/distribution:main
          # ghcr.io/distribution/distribution:edge
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=sha
            type=edge
          labels: |
            org.opencontainers.image.title=Distribution
            org.opencontainers.image.description=The toolkit to pack, ship, store, and deliver container content
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build artifacts
        uses: docker/bake-action@v4
        with:
          targets: artifact-all
          provenance: false
      -
        name: Move artifacts
        run: |
          mv ./bin/**/* ./bin/
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: registry
          path: ./bin/*
          if-no-files-found: error
      -
        name: Build image
        uses: docker/bake-action@v4
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: image-all
          push: true
  check-release: # make sure commits are valid for a target branch
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}
      # - name: show commit message
      #   run: |
      #     git log --oneline --no-decorate --no-color --pretty=format:"%s" -1
      - name: temporarily merge PR branch
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git merge origin/${{ github.event.pull_request.head.ref }}
      - name: test unsetting vars
        run: |
          echo $GITHUB_EVENT_PATH
          echo $GITHUB_ACTIONS
          echo $GITHUB_EVENT_NAME
      - name: test unsetting vars
        run: |
          unset GITHUB_EVENT_PATH && echo $GITHUB_EVENT_PATH
          unset GITHUB_ACTIONS && echo $GITHUB_ACTIONS
          unset GITHUB_EVENT_NAME && echo $GITHUB_EVENT_NAME
      - name: test unsetting vars
        run: |
          echo $GITHUB_EVENT_PATH
          echo $GITHUB_ACTIONS
          echo $GITHUB_EVENT_NAME
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic_release
        with:
          dry_run: true
          ci: false
          semantic_version: 22.0.5
          extra_plugins: |
            conventional-changelog-conventionalcommits
