name: release

on:
  schedule:
    - cron:  '0 0 1 * *' # run release monthly
  workflow_dispatch: # allow a release to be triggered manually

env:
  GHCR_SLUG: ghcr.io/${{ github.repository_owner }}/distribution
  DOCKERHUB_SLUG: distribution/distribution

permissions: # Needed so the reusable workflow has the permissions it needs
  contents: write # to create GitHub release (cycjimmy/semantic-release-action)
  id-token: write # to write to GHCR
  packages: write # to write to GHCR

jobs:
  build-branch-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # No shallow clone, we need all history
      - name: generate matrix
        id: generate-matrix
        shell: bash
        run: |
          branches=('main' 'alpha' 'beta' 'rc')
          regex='^([0-9])?(\.([0-9]|x))?\.x$' # matches branches like 1.x or 2.0.x

          for branch in $(git for-each-ref --format='%(refname)' refs/heads/ | cut -d/ -f3-); do
              if [[ $branch =~ $regex ]]; then
                  branches+=("$branch")
              fi
          done

          echo "matrix=$(printf '%s\n' "${branches[@]}" | jq -R . | jq -s .)" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
  run-release:
    needs: build-branch-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-branch-matrix.outputs.matrix) }}
    uses: ./.github/workflows/release.yml
    with:
      branch: ${{ matrix.value }}
